if(NOT DEFINED CLANG_FORMAT)
  message(FATAL_ERROR "CLANG_FORMAT variable not set")
endif()
if(NOT DEFINED FILES)
  message(FATAL_ERROR "FILES variable not set")
endif()
foreach(file IN LISTS FILES)
  if(EXISTS "${file}")
    execute_process(COMMAND "${CLANG_FORMAT}" -i "${file}")
  endif()
endforeach()
